// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var main;

  window.addEventListener('load', function() {
    return FastClick.attach(document.body);
  }, false);

  main = angular.module('TodoGPS', []);

  main.controller('mainController', function($scope, $http) {
    navigator.geolocation.watchPosition(function(position) {
      $scope.loc = position.coords;
      return console.log(position.coords);
    });
    $scope.formData = {};
    $http.get('https://todogps.herokuapp.com/api/todos').success(function(data) {
      return $scope.todos = data;
    }).error(function(data) {
      return console.log(data);
    });
    $scope.createTodo = function() {
      return $http.post('https://todogps.herokuapp.com/api/todos', $scope.formData).success(function(data) {
        $scope.formData = {};
        return $scope.todos = data;
      }).error(function(data) {
        return console.log(data);
      });
    };
    return $scope.deleteTodo = function(id) {
      return $http["delete"]('https://todogps.herokuapp.com/api/todos/' + id).success(function(data) {
        return $scope.todos = data;
      });
    };
  });

}).call(this);
